# Generated by Django 5.2.2 on 2025-06-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='std_id',
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('H', 'High'), ('M', 'Medium')], default='L', max_length=1),
        ),
    ]
